In [21]:
#실습 6. 사이클타임을 표 모양으로 정리하기
import csv

with open('data/10_mct_tool.csv', 'r', encoding='utf-8') as f:
    reader = csv.reader(f)
    header = next(reader)
    body = list(reader)

cycle_time = [int(value[1]) for value in body[:12]]

import numpy as np

ct = np.array(cycle_time)

ct_34 = ct.reshape(3,4)

print(ct_34)

[[21156 15611 15633 15601]
 [15607 15557 15557 15636]
 [15600 15634 21207 15554]]


In [22]:
ct_1 = ct_34.flatten()
print(ct_1)

[21156 15611 15633 15601 15607 15557 15557 15636 15600 15634 21207 15554]


In [23]:
cycle_time_change = ct_1.copy() #현재 변수에 담긴 값을 그대로 복제

cycle_time_change[0] = 0
print(cycle_time_change)

[    0 15611 15633 15601 15607 15557 15557 15636 15600 15634 21207 15554]


In [24]:
temp = np.array([27, 30, 33, 27, 28])

temp_2d = np.array([[27, 30, 33, 27, 28], [87, 79, 92, 81, 85], [27, 30, 33, 27, 28], [87, 79, 92, 81, 85]])

print(temp_2d[0:3])

print(temp_2d[0:5, 0])


[[27 30 33 27 28]
 [87 79 92 81 85]
 [27 30 33 27 28]]
[27 87 27 87]


In [25]:
#실습1. 회전수 전체 다 꺼내기

rot = []

for value in body[:10]:
    rot.append(int(value[4].replace('*', '')))

rot = np.array(rot)

print(rot)

print(rot[0])
print(rot[-1])
print(rot[1:4])
print(rot[::2])



[4603 4603 4967 4603 4603 4603 4603 4987 4603 3632]
4603
3632
[4603 4967 4603]
[4603 4967 4603 4603 4603]


In [26]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print()

In [27]:
maxval = rot.max()
minval = rot.min()
rot_norm = (rot - minval) / (maxval - minval)
print(rot_norm)

[0.71660517 0.71660517 0.98523985 0.71660517 0.71660517 0.71660517
 0.71660517 1.         0.71660517 0.        ]


In [28]:
# 정규화: 값의 범위를 0~1사이로 정리하는 것
# 단위가 다른 값들 비교하기 위해 필요함
# (값 - 최솟값) / (최댓값 - 최솟값) : 정규화 식

arr_scores = np.array([61, 78, 59, 20, 83])

print(arr_scores >= 60)

[ True  True False False  True]


In [29]:
list_scores = [61, 78, 59, 20, 83]

for score in list_scores:
    print(score >= 60) 

True
True
False
False
True


In [30]:
print(arr_scores[arr_scores >= 60])
# 조건을 만족하는 값만 남김
# 60을 넘는 값은 어떤 값인지를 알 수 있음
# 조건을 만족하지 못한다면 버려버림
# 불리언 인덱싱 결과는 기존 크기와 같거나 작아짐



[61 78 83]


In [31]:
print(np.where(arr_scores >= 60, 1, 0)) 



[1 1 0 0 1]


In [32]:
arr_temps = np.array([18, 15, 24, 30, 33, 21, 15])

# 쾌적 온도 구간만 출력

print(arr_temps[(25>= arr_temps) & (arr_temps>=18)])

# and 연산자는 값 하나에 대한 연산을 함 (배열에서 사용 불가)

[18 24 21]


In [33]:
rpm = np.array(body)[:,4].astype(float)
elec = np.array(body)[:,3].astype(float)

print(rpm < 2000)

print(rpm[rpm < 2000])

print((rpm < 2000) | (elec > 25))

total_count = len(rpm)
rpm_low2000_count = (rpm < 2000).sum()
rpm_low2000_torque_high25_count = ((rpm<2000) | (elec > 25)).sum()

print(f"저회전 횟수: {rpm_low2000_count}, 저회전 비율: {rpm_low2000_count/total_count}")
print(f"저회전이면서 토크가 높은 횟수: {rpm_low2000_torque_high25_count}, 저회전이면서 토크가 높은 횟수와 비율: {rpm_low2000_torque_high25_count / total_count}")


[False False False False False False False False False False False False
 False False False False False False False False  True False False  True
 False False  True False False False False False  True False False False
 False False False False]
[  58. 1216. 1217. 1241.]
[False False  True False False False False  True False  True False False
 False False False False False False False False  True False False  True
 False False  True False False False False False  True False False  True
 False  True False False]
저회전 횟수: 4, 저회전 비율: 0.1
저회전이면서 토크가 높은 횟수: 9, 저회전이면서 토크가 높은 횟수와 비율: 0.225


In [34]:
print(total_count)

40


In [35]:
# 최댓값: max()
# 최솟값: min()
# 분산: var()
# 표준편차: std()
# 중앙값: median()


In [36]:
# 실습: 회전수의 평균, 중앙값, 분산, 표준편차 구하기

rpm = np.array(body)[:,4].astype(float)
avg_rpm = round(rpm.mean(), 1)
median_rpm = round((np.median(rpm)),1)
var_rpm = round(rpm.var(),1)
std_rpm = round(rpm.std(), 1)

print(f"회전수 평균: {avg_rpm}, 중앙값: {median_rpm}, 분산: {var_rpm}, 표준편차: {std_rpm}")

회전수 평균: 4212.6, 중앙값: 4603.0, 분산: 1310886.8, 표준편차: 1144.9


In [37]:
# axis 개념 (row, column의 방향을 지정해줌.)
# axis=0은 위에서 아래로, 즉 열방향. 한개의 column의 값을 모음
# axis=1은 좌에서 우로(우에서 좌로), 즉 row 방향. 한 row의 값을 모음

import numpy as np
# 시험 점수
movies = np.array([["Runtime", "Relese_year", "Age_Rating"],
            [130, 2026, 13],
            [156, 2026, 15]
])

movies_body = movies[1:,].astype(int)

print("movies_body.mean():", movies_body.mean(axis=0))
# 결론적으로 평균 결과는 float 배열로 반환됨

# 행별 평균을 구하는 방법: axis = 1로 지정하면 됨
# 열별 평균을 구하는 방법: axis = 0으로 지정하면 됨
# 사실 current data set 기준으로는 행별 평균은 의미가 없음 because 단위가 다른 값이 섞여있다
# 특히 설비 데이터는 열마다 단위가 다르기 때문에 행별 평균을 내는 것은 의미가 없다. axis=0을 압도적으로 많이 사용



movies_body.mean(): [ 143. 2026.   14.]


In [ ]:
with open("data/10_mct_tool.csv", "r", encoding="utf-8") as f:
    reader = csv.reader(f)
    header = next(reader)
    data_body = np.array(list(reader)).astype(float)


torque = data_body[:, -1]
rpm = data_body[:,-2]

print(f"회전수 평균: {rpm.mean()}, 토크 평균: {torque.mean()}")
#np.median(torque, axis=0)

회전수 평균: 4212.625, 토크 평균: 10.7


In [51]:
rmp = np.loadtxt('data/10_mct_tool.csv',
                  delimiter = ",",
                  skiprows =1,
                  usecols = 4
                )

print(rpm.shape, rpm.dtype)

(40,) float64


In [ ]:
datas = np.loadtxt('data/10_mct_tool.csv',
                  delimiter = ",",
                  skiprows =1,
                  usecols = (0,1,2,3,4,5)
                )

print(datas)

[[2.1156e+04 3.0000e+01 1.5440e+01 4.6030e+03 2.0000e+00]
 [1.5611e+04 3.0000e+01 1.8690e+01 4.6030e+03 2.0000e+00]
 [1.5633e+04 3.0000e+01 6.2480e+01 4.9670e+03 2.1000e+01]
 [1.5601e+04 3.0000e+01 1.8370e+01 4.6030e+03 2.0000e+00]
 [1.5607e+04 2.9000e+01 1.8670e+01 4.6030e+03 3.0000e+00]
 [1.5557e+04 3.0000e+01 1.4980e+01 4.6030e+03 2.0000e+00]
 [1.5557e+04 3.1000e+01 1.8400e+01 4.6030e+03 2.0000e+00]
 [1.5636e+04 3.1000e+01 6.2060e+01 4.9870e+03 3.0000e+00]
 [1.5600e+04 3.0000e+01 1.8550e+01 4.6030e+03 2.0000e+00]
 [1.5634e+04 3.0000e+01 6.4480e+01 3.6320e+03 1.4700e+02]
 [2.1207e+04 3.0000e+01 1.8840e+01 4.6030e+03 3.0000e+00]
 [1.5554e+04 3.0000e+01 2.4450e+01 4.6030e+03 2.0000e+00]
 [1.5600e+04 3.0000e+01 1.8510e+01 4.6030e+03 2.0000e+00]
 [1.5606e+04 3.0000e+01 1.9190e+01 4.6030e+03 3.0000e+00]
 [1.5612e+04 2.9000e+01 1.8420e+01 4.6030e+03 2.0000e+00]
 [1.5602e+04 3.0000e+01 1.8480e+01 4.6030e+03 3.0000e+00]
 [1.5602e+04 3.1000e+01 1.9050e+01 4.6030e+03 3.0000e+00]
 [1.5557e+04 3

In [ ]:
#실숩9. 불러오기부터 통계까지 한 흐름으로

rpm_torque = np.loadtxt('data/10_mct_tool.csv',
                  delimiter = ",",
                  skiprows =1,
                  usecols = (4,5)
                )

print(rpm_torque.shape, rpm_torque.dtype)

rpm = rpm_torque[:,0]
print(rpm[rpm<2000])
avg_rpmlow = rpm[rpm<2000].mean()

print(f"이상시점: {len(rpm[rpm<2000])}, 이상평균: {avg_rpmlow}, 전체평균: {round(rpm.mean(),1)}")

(40, 2) float64
[  58. 1216. 1217. 1241.]
이상시점: 4, 이상평균: 933.0, 전체평균: 4212.6


In [ ]:
F = 'data/11_diecasting_series.csv'
ct = np.genfromtxt(F,
                   delimiter=',',    # 값을 나누는 기호
                   skip_header=1,    # 첫 줄(제목)은 건너뜀
                   usecols=1)        # 2번째 열 = 사이클타임
print(ct.shape, ct.dtype)



In [62]:
#fancy indexing

vals = np.array([1, 2, 3, 4, 5])
pick = np.array([0, 4])

print(vals[pick]) # vals 배열에서 pcik 배열에 담긴 인덱스를 추출

[1 5]


In [63]:
vib = np.array([2.1, 2.3, 2.0, 5.8])
pick = np.array([0, 3])
print(vib[pick])

[2.1 5.8]


In [ ]:
# argsort는 배열에서 작은 순서대로 원래 배열의 인덱스를 출력
print(np.argsort(vib))

[2 0 1 3]


In [68]:
print(np.argsort(data_body[-3:, 2]))

[1 2 0]


In [69]:
col2 = data_body[:, 2].astype(float)

idx = np.argsort(col2)[-3:]

print(idx)

[ 6 37 36]


In [93]:
#실습 1. 최대 실린더압력이 가장 큰 시점 찾기
datas = np.loadtxt('data/11_diecasting_series.csv',
                  delimiter = ",",
                  skiprows =1,
                  usecols = (0,1,2,3,4)
                )

ti = datas[:,0]
cyl = datas[:,2] 

idx_cylmax = np.argmax(cyl)
timax = ti[idx_cylmax]

print(f"가장 큰 값이 있는 인덱스: {idx_cylmax}, 실제 사이클번호: {timax}, 최대실린더압력: {cyl[idx_cylmax]}")


가장 큰 값이 있는 인덱스: 24, 실제 사이클번호: 25.0, 최대실린더압력: 265.0


In [97]:
ct = datas[:,1]
idx_ctmax = np.argmax(ct)
print(f'사이클타임 - 평균: {ct.mean()}, 중앙값: {np.median(ct)}, 최댓값: {ct.max()}, 최솟값: {ct.min()}, 표준편차: {ct.std()}, 사이클타임이 제일 긴 시점: {ti[idx_ctmax]} ')
print(f'실린더 압력 - 평균: {cyl.mean()}, , 중앙값: {np.median(cyl)}, 최댓값: {cyl.max()}, 최솟값: {cyl.min()}, 표준편차: {cyl.std()}, 사이클타임이 제일 긴 시점: {ti[idx_cylmax]}')

사이클타임 - 평균: 201.21, 중앙값: 22.6, 최댓값: 6170.0, 최솟값: 20.6, 표준편차: 895.2074736618322, 사이클타임이 제일 긴 시점: 50.0 
실린더 압력 - 평균: 225.78, , 중앙값: 218.0, 최댓값: 265.0, 최솟값: 108.0, 표준편차: 44.34604379197766, 사이클타임이 제일 긴 시점: 25.0


In [100]:
arri = np.array([2.0, 2.1, 2.2, 7.0, 7.1])
change=np.diff(arri)
print(change)

[0.1 0.1 4.8 0.1]


In [105]:
ct_change = np.diff(ct)
print(np.abs(ct_change))
print("변화량이 가장 큰 부분의 index:", np.argmax(np.abs(ct_change)))
print("자리와 바로 다음 자리의 사이클 번호",ti[np.argmax(np.abs(ct_change))], ti[np.argmax(np.abs(ct_change))+1])

[1.0000e-01 3.0000e-01 0.0000e+00 1.0000e-01 1.0000e-01 1.0000e-01
 1.0000e-01 1.0000e-01 1.0000e-01 0.0000e+00 2.0000e-01 0.0000e+00
 1.0000e-01 2.0000e-01 2.0000e-01 1.0000e-01 5.0000e-01 1.0000e-01
 3.0000e-01 1.0000e-01 1.3000e+00 0.0000e+00 2.0000e-01 1.4600e+01
 3.0000e+00 1.0000e-01 1.0000e-01 1.0000e-01 1.0000e-01 2.1000e+00
 0.0000e+00 1.0000e-01 2.0000e-01 2.0000e-01 1.0000e-01 1.0000e-01
 1.0000e-01 2.0000e-01 0.0000e+00 1.0000e-01 2.0000e-01 6.1610e+02
 6.3100e+02 3.0000e-01 6.9600e+01 5.3100e+01 1.8472e+03 1.8492e+03
 6.1339e+03]
변화량이 가장 큰 부분의 index: 48
자리와 바로 다음 자리의 사이클 번호 49.0 50.0
