In [5]:
# narray: 배열 (우리가 학습했던 리스트와 다른 자료형)
# numpy에서 자료를 담는 그릇
# 같은 자료형만 담음 (ex. 정수 배열, 실수 배열)
# 정해진 형태를 가지고 잇음 (한 줄로 구성되어 있거나 표 모양)

# 리스트로 배열의 요소들에 *5릃 하는 코드 작성

tiems=0
type_list= [1, 2, 3, 4, 5]
times_5 = []
for num in type_list:
    times = num*5
    times_5.append(times)

print(times_5)

print(times_5 +[5])

[5, 10, 15, 20, 25]
[5, 10, 15, 20, 25, 5]


In [6]:
import numpy as np
np_array = np.array([1,2,3,4,5])

print(np_array)
print(np_array*5)


[1 2 3 4 5]
[ 5 10 15 20 25]


In [16]:
import csv, os

with open("data/10_mct_tool.csv", "r", encoding="utf-8") as f:
    reader = csv.reader(f)
    rows = list(csv.reader(f))

    header = rows[0]
    body = rows[1:]
    
    print(header)
    print(body)
   

['공구번호', '사이클타임', '온도', '전류', '회전수', '토크']
[['43000007', '21156', '30', '15.44', '4603', '2'], ['43000007', '15611', '30', '18.69', '4603', '2'], ['43000007', '15633', '30', '62.48', '4967', '21'], ['43000007', '15601', '30', '18.37', '4603', '2'], ['43000007', '15607', '29', '18.67', '4603', '3'], ['43000007', '15557', '30', '14.98', '4603', '2'], ['43000007', '15557', '31', '18.4', '4603', '2'], ['43000007', '15636', '31', '62.06', '4987', '3'], ['43000007', '15600', '30', '18.55', '4603', '2'], ['43000007', '15634', '30', '64.48', '3632', '147'], ['43000007', '21207', '30', '18.84', '4603', '3'], ['43000007', '15554', '30', '24.45', '4603', '2'], ['43000007', '15600', '30', '18.51', '4603', '2'], ['43000007', '15606', '30', '19.19', '4603', '3'], ['43000007', '15612', '29', '18.42', '4603', '2'], ['43000007', '15602', '30', '18.48', '4603', '3'], ['43000007', '15602', '31', '19.05', '4603', '3'], ['43000007', '15557', '31', '18.66', '4603', '2'], ['43000007', '15606', '30', '18.29',

In [22]:
#실습1
temps = [32, 30, 33, 29, 30, 31]
import numpy as np

F_temps = np.array(temps)
F_temps = F_temps*1.8+32
print(F_temps)
print(F_temps.dtype)

[89.6 86.  91.4 84.2 86.  87.8]
float64


In [33]:
temp = []
for value in body:
    temp.append(float(value[2]))
temp = np.array(temp)
F_temp = 1.8*temp+32

print(F_temp)

[86.  86.  86.  86.  84.2 86.  87.8 87.8 86.  86.  86.  86.  86.  86.
 84.2 86.  87.8 87.8 86.  84.2 86.  86.  86.  86.  84.2 86.  87.8 87.8
 86.  84.2 86.  86.  86.  84.2 84.2 86.  87.8 87.8 86.  86. ]


In [34]:
# for문을 짧게 작성하는 방법
# 리스트 컴프리헨션
# 리스트에_삽입할_값 for 변수 in 리스트명
# ex)) float(row[2]) for row in body

temp = np.array([float(value[2]) for value in body])
# 대괄호로 감싸주면 for 문을 돌면서 뽑아낸 온도값이
# 밖에 있는 대괄호 안에 하나씩 자동으로 들어감

F_temp = temp*1.8+32

print(F_temp)

[86.  86.  86.  86.  84.2 86.  87.8 87.8 86.  86.  86.  86.  86.  86.
 84.2 86.  87.8 87.8 86.  84.2 86.  86.  86.  86.  84.2 86.  87.8 87.8
 86.  84.2 86.  86.  86.  84.2 84.2 86.  87.8 87.8 86.  86. ]


In [37]:
# np.arrange로 일정간격 숫자 만들기
print(np.arange(3))

print(np.arange(10,0,-2))

[0 1 2]
[10  8  6  4  2]


In [40]:
# [0 2 4 6 8]

print(np.arange(0,10,2))

print(np.linspace(0,8,5,dtype=int))

print(np.zeros(5))

print(np.ones(3))


[0 2 4 6 8]
[0 2 4 6 8]
[0. 0. 0. 0. 0.]
[1. 1. 1.]


In [41]:
print(np.full(3,7))

[7 7 7]


In [ ]:
# 배열을 만든다는 것 자체가 어떠한 값들을 모아두겠다는 말
# 초기화 배열을 빈 배열이 아니도록 만드는 이유는 
# 크기를 미리 정해두고 하나씩 채우기 위함

In [ ]:
#실습 2. 전류 구간을 가은 간격의 값으로 채우기

print(np.linspace(0,70,8,dtype=int))

[ 0 10 20 30 40 50 60 70]


In [45]:
#실습3. 측정 순번 배열 만들기

num = np.arange(0,40,5)
print(num)

[ 0  5 10 15 20 25 30 35]


In [ ]:
#ndim: 배열의 차원을 출력해줌 = 리스트 안의 리스트의 개수
# 직접 리스트를 입력한 배열의 경우 보기 좋은
# but 변수로 배열을 만드는 경우
# 해당 변수에 담긴 값을 확인하기는 번거로움
# 배열로 바꾸고자 하는 리스트의 길이가 매우 길 경우 확인이 불편함
# 그럴 때 간단하게 배열의 차원을 확인하기 위해서 사용

# print(a.ndim)
# print(b.ndim)

# ndim은 속성이기 때문에 괄호를 사용하지 않음
# 1차원은 값이 왼쪽에서 오른쪽으로 나열되어있는 형태
# 2차원은 표 형태로 행과 열이 있는 형태로설비 데이터는 보통 행과 열로 이루어져있고,
# 행= 시점, 열 = 센서값을 가진 2차원의 표 형태



In [ ]:
d2 = np.array([[1,2],[2,3]])

print(len(d2)) # 배열의 길이
print(d2.size) # 배열 원소읙 개수

2
4


In [48]:
ex4=np.array([[30, 15.44], [30, 18.69], [30, 62.48], [30, 18.37]])
print(ex4.ndim)
print(ex4.shape)
print(ex4.size)



2
(4, 2)
8


In [ ]:
#실습5

elec = np.array([15.44, 18.69, 62.48, 18.37])

print(elec.dtype)

elec_int = elec.astype(int)

print(elec_int)

float64
[15 18 62 18]


In [52]:
## =============================
# 1차원 -> 2차원 배열로 바꾸기
# reshape(행,열)

arr999 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

arr9999 = arr999.reshape(2,6)

print(arr9999)



[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [53]:
arr9 = arr9999.flatten()

print(arr9)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
