In [ ]:
# np.clip(배열, 하한값, 상한값)
# 값의 길이가 달라지지 않음
# 정해둔 하한값과 상한값 밖의 값들은 하한값과 상한값으로 변경됨
import numpy as np

tall = np.array([153, 162, 178, 198, 203, 163])
fixed = np.clip(tall, 158, 178)
print(fixed)

[158 162 178 178 178 163]


In [ ]:
fixed2 = tall[(tall<=178) & (tall>=158)]

In [ ]:
print(fixed2)

[162 178 163]


In [ ]:
#실습3
pressure_cyl = np.loadtxt('data/11_diecasting_series.csv',
                  delimiter = ",",
                  skiprows =1,
                  usecols = 2
                )

pressure_cyl[0] = 9999

sum__err_pressure_cyl = pressure_cyl.sum()

avg__err_pressure_cyl = sum__err_pressure_cyl / len(pressure_cyl)

pressure_cyl_adj = np.clip(pressure_cyl, 100, 300)

avg_pressure_cly_adj = pressure_cyl_adj.sum() / len(pressure_cyl)

print(f"오류가 있을때 평균: {avg__err_pressure_cyl}")
print(f"조정 후 평균: {avg_pressure_cly_adj}")

오류가 있을때 평균: 421.48
조정 후 평균: 227.5


In [ ]:
# np.cumsum(변수)
# 누적합을 구해줌
# 지금까지는 반복문을 돌면서 변수에 값을 더해 직접 누적합을 구했으나
# comsum을 사용하면 누적합을 바로 확인할 수 잇음
# cumsum은 배열의 전체 누적값을 반환하는 것이 아니라
# 기존 배열과 동일한 길이라 각 값을 하나의 누적합 배열로 변환

new_arr = np.array([1, 2, 3, 4, 5])
print(np.cumsum(new_arr))

[ 1  3  6 10 15]


In [ ]:
ct = np.loadtxt('data/11_diecasting_series.csv',
                  delimiter = ",",
                  skiprows =1,
                  usecols = 1
                )

label = np.where(ct>=1000, "잼", np.where(ct>=50, "경고", "정상"))
kind, count = np.unique(label, return_counts=True)


print(f"정상:{count[-1]}, 경고:{count[0]}, 잼:{count[1]}, 비율은 순서대로 {count[-1]/len(ct)}, {count[0]/len(ct)}, {count[1]/len(ct)} ")

정상:46, 경고:2, 잼:2, 비율은 순서대로 0.92, 0.04, 0.04 


In [ ]:
vib = np.array([2.1, 2.3, 6.2, 2.0])

print(np.any(vib > 5))
print(np.all(vib > 5))
first = np.argmax(vib>5)
print(first)

# 참 거짓 배열에 argmax를 적용하면 true를 만족하는 최초의 값의 index를 알려줌

True
False
2


In [ ]:
# concatenate: 1차원 배열을 이어주는 것. 반환 결과도 1차원 배열로 나옴 = 가로로 이어 붙이기
# stack: 위아래로 배열을 이어주는 것. 붙이는 배열들의 열 개수가 같아야함

am = np.array([1,2,3,4,5])
pm = np.array([6,7,8,9,10])

print(np.concatenate([am, pm]))
print(np.stack([am,pm]))

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
# stak은 axis=1을 통해 세로방향 붙이기도 가능
print(np.stack([am,pm], axis=1))

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [ ]:
datas = np.loadtxt('data/11_diecasting_series.csv',
                  delimiter = ",",
                  skiprows =1,
                  usecols = (0,1,2,3,4)
                )

Time = datas[:,0]
ct = datas[:,1]
pressure_cyl = datas[:,2]
pressure_ju = datas[:,3]
force = datas[:,4]

datas2 = np.stack([Time, ct, pressure_cyl, pressure_ju, force], axis=1)
print(datas2)

[[1.0000e+00 2.0700e+01 2.1400e+02 1.0370e+03 2.5800e+02]
 [2.0000e+00 2.0600e+01 2.1400e+02 1.0380e+03 2.5500e+02]
 [3.0000e+00 2.0900e+01 2.1800e+02 1.0530e+03 2.5900e+02]
 [4.0000e+00 2.0900e+01 2.1800e+02 1.0540e+03 2.5700e+02]
 [5.0000e+00 2.0800e+01 2.1400e+02 1.0380e+03 2.5500e+02]
 [6.0000e+00 2.0900e+01 2.1400e+02 1.0370e+03 2.5700e+02]
 [7.0000e+00 2.0800e+01 2.1800e+02 1.0530e+03 2.5700e+02]
 [8.0000e+00 2.0900e+01 2.1700e+02 1.0520e+03 2.5800e+02]
 [9.0000e+00 2.0800e+01 2.1800e+02 1.0530e+03 2.5700e+02]
 [1.0000e+01 2.0900e+01 2.1700e+02 1.0520e+03 2.5800e+02]
 [1.1000e+01 2.0900e+01 2.1500e+02 1.0400e+03 2.5400e+02]
 [1.2000e+01 2.0700e+01 2.1800e+02 1.0540e+03 2.5800e+02]
 [1.3000e+01 2.0700e+01 2.1400e+02 1.0370e+03 2.5800e+02]
 [1.4000e+01 2.0800e+01 2.1700e+02 1.0520e+03 2.5500e+02]
 [1.5000e+01 2.0600e+01 2.1700e+02 1.0510e+03 2.5800e+02]
 [1.6000e+01 2.0800e+01 2.1400e+02 1.0380e+03 2.5500e+02]
 [1.7000e+01 2.0700e+01 2.1400e+02 1.0380e+03 2.5800e+02]
 [1.8000e+01 2

In [ ]:
datas = np.loadtxt('data/11_diecasting_series.csv',
                  delimiter = ",",
                  skiprows =1,
                  usecols = (0,1,2,3,4)
                )
data = datas[:,0:3]

time_maxct = Time[np.argmax(data[:,0])]
maxct = ct[np.argmax(data[:,0])]
print(f'사이클타임이 가장 컸던 시점:{time_maxct}, 사이클 타임 최대값:{maxct}')

change_ct = np.diff(data[:,0])
idx_max_chang_Ct = np.argmax(change_ct)
print(f'급변하는 구간= 시점 {Time[idx_max_chang_Ct]}->{Time[idx_max_chang_Ct+1]}')

label = np.where((data[:,0]>=50) & (data[:,2]<150), "경고", "정상")

kind, count = np.unique(label, return_counts=True)
print(kind, count)
print(f'경고비율:{count[0]/len(label)}')

사이클타임이 가장 컸던 시점:50.0, 사이클 타임 최대값:6170.0
급변하는 구간= 시점 1.0->2.0
['경고' '정상'] [ 1 49]
경고비율:0.02


In [ ]:
import numpy as np

data = np.loadtxt(
    'data/11_diecasting_series.csv',
    delimiter=',',
    skiprows=1,
    usecols=(0, 1, 2)
)

time = data[:, 0]
ct = data[:, 1]
pressure_cyl = data[:, 2]


idx_max_ct = np.argmax(ct)

time_max_ct = time[idx_max_ct]
max_ct = ct[idx_max_ct]

print(f'사이클타임이 가장 컸던 시점: {time_max_ct}, 사이클타임 최대값: {max_ct}')


change_ct = np.abs(np.diff(ct))
idx_max_change_ct = np.argmax(change_ct)

print(
    f'사이클타임 변화량이 가장 컸던 구간: '
    f'시점 {time[idx_max_change_ct]} -> {time[idx_max_change_ct + 1]}, '
    f'변화량: {change_ct[idx_max_change_ct]}'
)

warning = (ct >= 50) | (pressure_cyl < 150)

warning_count = warning.sum()
warning_ratio = warning_count / len(warning)

print(f'경고 개수: {warning_count}')
print(f'경고 비율: {warning_ratio}')


top3_idx = np.argsort(ct)[::-1][:3]

print('사이클타임 상위 3개:')
for idx in top3_idx:
    print(f'시점: {time[idx]}')

사이클타임이 가장 컸던 시점: 50.0, 사이클타임 최대값: 6170.0
사이클타임 변화량이 가장 컸던 구간: 시점 49.0 -> 50.0, 변화량: 6133.9
경고 개수: 6
경고 비율: 0.12
사이클타임 상위 3개:
시점: 50.0
시점: 48.0
시점: 43.0


In [ ]:
import pandas as pd

In [ ]:
# pandas에서 sereis라는건 표에서 열을 나타냄. 그러니까 즉, 같은 종류를 가진 값들을 말함
df = pd.read_csv("data/12_metro_compressor.csv")
dfs = pd.read_csv("data/12_metro_compressor_semicolon.csv")

In [ ]:
print(df)

                    측정시각  압축압력  배출압력  저장압력  오일온도  모터전류 가동상태
0    2020-02-27 06:38:47  9.30 -0.02  9.30  51.3  6.04   가동
1    2020-02-27 07:28:21  8.55 -0.02  8.55  56.8  0.04   정지
2    2020-02-27 08:17:54  8.67 -0.02  8.67  55.7  0.03   정지
3    2020-02-27 09:07:27  9.76 -0.02  9.76   NaN  3.81   가동
4    2020-02-27 09:57:01  8.49 -0.02  8.49  55.3  0.04   정지
..                   ...   ...   ...   ...   ...   ...  ...
195  2020-03-06 15:03:00  8.72 -0.02  8.72  60.7  5.81   가동
196  2020-03-06 15:52:33  8.85 -0.02  8.85  61.9  0.04   정지
197  2020-03-06 16:42:06  9.74 -0.02  9.74  73.0  3.77   가동
198  2020-03-06 17:31:39  9.89 -0.02  9.89  72.5  3.82   가동
199  2020-03-06 18:21:13  9.87 -0.02  9.87  71.7  3.75   가동

[200 rows x 7 columns]


In [ ]:
import os
print(os.getcwd())

c:\Users\user\Desktop\Posco\test


In [ ]:
print("데이터 크기:",df.shape)
rows, cols = df.shape
print(rows, cols)

데이터 크기: (200, 7)
200 7


In [ ]:
# 모든 열(항목) 이름 출력
print("항목:", df.columns)
print("항목:", df.columns.tolist()) 
# index를 0,1,2 이런걸 사용하는게 아니라 측정시간, 압축압력 등의 제목이 곧 인덱스로 사용가능




항목: Index(['측정시각', '압축압력', '배출압력', '저장압력', '오일온도', '모터전류', '가동상태'], dtype='object')
항목: ['측정시각', '압축압력', '배출압력', '저장압력', '오일온도', '모터전류', '가동상태']


In [ ]:
print(df["오일온도"].values) # numpy 배열임

[51.3 56.8 55.7  nan 55.3 57.1 56.6 56.6 57.2 57.4 57.7 57.2 58.9 57.6
 59.6 55.4 56.  56.  53.6 50.1 53.3 51.2 52.  50.4 51.  51.  50.5 51.8
 53.7 54.6 57.9 55.3 56.8 57.1 57.6 56.7 57.5 57.8 58.5 58.1 56.9 58.6
 58.5 56.6 57.4 53.8 55.5 55.  53.2 54.3 66.3 57.6 66.6 58.1 66.9 58.1
 67.2 58.9 67.2 59.5 67.5 59.6 65.5 65.8 62.6 71.8 61.2 71.2 60.6 70.6
 60.5 70.4 60.5 70.8 60.2 71.7 60.  71.4 59.1 67.6 57.4 65.1 69.6 67.9
 61.5 63.1 71.6 69.  70.6 62.2 68.1 69.8 73.2 61.3 73.  66.2 59.5 74.6
 67.  53.5 71.  60.6 70.6 72.  72.3 61.5 64.7 63.  63.7 75.  61.2 73.4
 63.9 70.8 67.3 63.1 66.5 60.2 64.7 69.2 71.8 67.5 68.3 72.6 62.9 64.
 61.4 58.8 67.2 61.1 66.8 57.3 61.8 66.7 67.2 61.1 64.1 60.9 66.2 65.
 67.7 61.3 72.8 67.6 64.5 72.7 70.7 71.8 71.6 61.  60.2 68.2 63.2 71.6
 59.7 66.3 58.8 73.1 61.7 64.8 61.6 66.1 75.  65.  73.6 68.5 69.7 68.1
 60.4 69.1 62.9 73.7 62.6 63.1 68.1 64.8 59.4 57.  63.3 65.9 64.1 60.3
 64.  65.2 70.5 58.7 58.8 71.5 70.2 64.3 69.1 73.4 62.7 60.6 67.5 60.7
 61.9 73

In [ ]:
# "가동상태" 열의 고유값 개수와 고유갑별 총 갯수 출력

state = df["가동상태"].values

name, count = np.unique(state)