In [31]:
# np.clip(배열, 하한값, 상한값)
# 값의 길이가 달라지지 않음
# 정해둔 하한값과 상한값 밖의 값들은 하한값과 상한값으로 변경됨
import numpy as np

tall = np.array([153, 162, 178, 198, 203, 163])
fixed = np.clip(tall, 158, 178)
print(fixed)

[158 162 178 178 178 163]


In [32]:
fixed2 = tall[(tall<=178) & (tall>=158)]

In [33]:
print(fixed2)

[162 178 163]


In [34]:
#실습3
pressure_cyl = np.loadtxt('data/11_diecasting_series.csv',
                  delimiter = ",",
                  skiprows =1,
                  usecols = 2
                )

pressure_cyl[0] = 9999

sum__err_pressure_cyl = pressure_cyl.sum()

avg__err_pressure_cyl = sum__err_pressure_cyl / len(pressure_cyl)

pressure_cyl_adj = np.clip(pressure_cyl, 100, 300)

avg_pressure_cly_adj = pressure_cyl_adj.sum() / len(pressure_cyl)

print(f"오류가 있을때 평균: {avg__err_pressure_cyl}")
print(f"조정 후 평균: {avg_pressure_cly_adj}")

오류가 있을때 평균: 421.48
조정 후 평균: 227.5


In [35]:
# np.cumsum(변수)
# 누적합을 구해줌
# 지금까지는 반복문을 돌면서 변수에 값을 더해 직접 누적합을 구했으나
# comsum을 사용하면 누적합을 바로 확인할 수 잇음
# cumsum은 배열의 전체 누적값을 반환하는 것이 아니라
# 기존 배열과 동일한 길이라 각 값을 하나의 누적합 배열로 변환

new_arr = np.array([1, 2, 3, 4, 5])
print(np.cumsum(new_arr))

[ 1  3  6 10 15]


In [36]:
ct = np.loadtxt('data/11_diecasting_series.csv',
                  delimiter = ",",
                  skiprows =1,
                  usecols = 1
                )

label = np.where(ct>=1000, "잼", np.where(ct>=50, "경고", "정상"))
kind, count = np.unique(label, return_counts=True)


print(f"정상:{count[-1]}, 경고:{count[0]}, 잼:{count[1]}, 비율은 순서대로 {count[-1]/len(ct)}, {count[0]/len(ct)}, {count[1]/len(ct)} ")

정상:46, 경고:2, 잼:2, 비율은 순서대로 0.92, 0.04, 0.04 


In [37]:
vib = np.array([2.1, 2.3, 6.2, 2.0])

print(np.any(vib > 5))
print(np.all(vib > 5))
first = np.argmax(vib>5)
print(first)

# 참 거짓 배열에 argmax를 적용하면 true를 만족하는 최초의 값의 index를 알려줌

True
False
2


In [38]:
# concatenate: 1차원 배열을 이어주는 것. 반환 결과도 1차원 배열로 나옴 = 가로로 이어 붙이기
# stack: 위아래로 배열을 이어주는 것. 붙이는 배열들의 열 개수가 같아야함

am = np.array([1,2,3,4,5])
pm = np.array([6,7,8,9,10])

print(np.concatenate([am, pm]))
print(np.stack([am,pm]))

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [39]:
# stak은 axis=1을 통해 세로방향 붙이기도 가능
print(np.stack([am,pm], axis=1))

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [40]:
datas = np.loadtxt('data/11_diecasting_series.csv',
                  delimiter = ",",
                  skiprows =1,
                  usecols = (0,1,2,3,4)
                )

Time = datas[:,0]
ct = datas[:,1]
pressure_cyl = datas[:,2]
pressure_ju = datas[:,3]
force = datas[:,4]

datas2 = np.stack([Time, ct, pressure_cyl, pressure_ju, force], axis=1)
print(datas2)

[[1.0000e+00 2.0700e+01 2.1400e+02 1.0370e+03 2.5800e+02]
 [2.0000e+00 2.0600e+01 2.1400e+02 1.0380e+03 2.5500e+02]
 [3.0000e+00 2.0900e+01 2.1800e+02 1.0530e+03 2.5900e+02]
 [4.0000e+00 2.0900e+01 2.1800e+02 1.0540e+03 2.5700e+02]
 [5.0000e+00 2.0800e+01 2.1400e+02 1.0380e+03 2.5500e+02]
 [6.0000e+00 2.0900e+01 2.1400e+02 1.0370e+03 2.5700e+02]
 [7.0000e+00 2.0800e+01 2.1800e+02 1.0530e+03 2.5700e+02]
 [8.0000e+00 2.0900e+01 2.1700e+02 1.0520e+03 2.5800e+02]
 [9.0000e+00 2.0800e+01 2.1800e+02 1.0530e+03 2.5700e+02]
 [1.0000e+01 2.0900e+01 2.1700e+02 1.0520e+03 2.5800e+02]
 [1.1000e+01 2.0900e+01 2.1500e+02 1.0400e+03 2.5400e+02]
 [1.2000e+01 2.0700e+01 2.1800e+02 1.0540e+03 2.5800e+02]
 [1.3000e+01 2.0700e+01 2.1400e+02 1.0370e+03 2.5800e+02]
 [1.4000e+01 2.0800e+01 2.1700e+02 1.0520e+03 2.5500e+02]
 [1.5000e+01 2.0600e+01 2.1700e+02 1.0510e+03 2.5800e+02]
 [1.6000e+01 2.0800e+01 2.1400e+02 1.0380e+03 2.5500e+02]
 [1.7000e+01 2.0700e+01 2.1400e+02 1.0380e+03 2.5800e+02]
 [1.8000e+01 2

In [41]:
datas = np.loadtxt('data/11_diecasting_series.csv',
                  delimiter = ",",
                  skiprows =1,
                  usecols = (0,1,2,3,4)
                )
data = datas[:,0:3]

time_maxct = Time[np.argmax(data[:,0])]
maxct = ct[np.argmax(data[:,0])]
print(f'사이클타임이 가장 컸던 시점:{time_maxct}, 사이클 타임 최대값:{maxct}')

change_ct = np.diff(data[:,0])
idx_max_chang_Ct = np.argmax(change_ct)
print(f'급변하는 구간= 시점 {Time[idx_max_chang_Ct]}->{Time[idx_max_chang_Ct+1]}')

label = np.where((data[:,0]>=50) & (data[:,2]<150), "경고", "정상")

kind, count = np.unique(label, return_counts=True)
print(kind, count)
print(f'경고비율:{count[0]/len(label)}')

사이클타임이 가장 컸던 시점:50.0, 사이클 타임 최대값:6170.0
급변하는 구간= 시점 1.0->2.0
['경고' '정상'] [ 1 49]
경고비율:0.02


In [42]:
import numpy as np

data = np.loadtxt(
    'data/11_diecasting_series.csv',
    delimiter=',',
    skiprows=1,
    usecols=(0, 1, 2)
)

time = data[:, 0]
ct = data[:, 1]
pressure_cyl = data[:, 2]


idx_max_ct = np.argmax(ct)

time_max_ct = time[idx_max_ct]
max_ct = ct[idx_max_ct]

print(f'사이클타임이 가장 컸던 시점: {time_max_ct}, 사이클타임 최대값: {max_ct}')


change_ct = np.abs(np.diff(ct))
idx_max_change_ct = np.argmax(change_ct)

print(
    f'사이클타임 변화량이 가장 컸던 구간: '
    f'시점 {time[idx_max_change_ct]} -> {time[idx_max_change_ct + 1]}, '
    f'변화량: {change_ct[idx_max_change_ct]}'
)

warning = (ct >= 50) | (pressure_cyl < 150)

warning_count = warning.sum()
warning_ratio = warning_count / len(warning)

print(f'경고 개수: {warning_count}')
print(f'경고 비율: {warning_ratio}')


top3_idx = np.argsort(ct)[::-1][:3]

print('사이클타임 상위 3개:')
for idx in top3_idx:
    print(f'시점: {time[idx]}')

사이클타임이 가장 컸던 시점: 50.0, 사이클타임 최대값: 6170.0
사이클타임 변화량이 가장 컸던 구간: 시점 49.0 -> 50.0, 변화량: 6133.9
경고 개수: 6
경고 비율: 0.12
사이클타임 상위 3개:
시점: 50.0
시점: 48.0
시점: 43.0


In [43]:
import pandas as pd

In [44]:
# pandas에서 sereis라는건 표에서 열을 나타냄. 그러니까 즉, 같은 종류를 가진 값들을 말함
df = pd.read_csv("data/12_metro_compressor.csv")
dfs = pd.read_csv("data/12_metro_compressor_semicolon.csv")

In [45]:
print(df)

                    측정시각  압축압력  배출압력  저장압력  오일온도  모터전류 가동상태
0    2020-02-27 06:38:47  9.30 -0.02  9.30  51.3  6.04   가동
1    2020-02-27 07:28:21  8.55 -0.02  8.55  56.8  0.04   정지
2    2020-02-27 08:17:54  8.67 -0.02  8.67  55.7  0.03   정지
3    2020-02-27 09:07:27  9.76 -0.02  9.76   NaN  3.81   가동
4    2020-02-27 09:57:01  8.49 -0.02  8.49  55.3  0.04   정지
..                   ...   ...   ...   ...   ...   ...  ...
195  2020-03-06 15:03:00  8.72 -0.02  8.72  60.7  5.81   가동
196  2020-03-06 15:52:33  8.85 -0.02  8.85  61.9  0.04   정지
197  2020-03-06 16:42:06  9.74 -0.02  9.74  73.0  3.77   가동
198  2020-03-06 17:31:39  9.89 -0.02  9.89  72.5  3.82   가동
199  2020-03-06 18:21:13  9.87 -0.02  9.87  71.7  3.75   가동

[200 rows x 7 columns]


In [46]:
import os
print(os.getcwd())

c:\Users\user\Desktop\Posco\test


In [47]:
print("데이터 크기:",df.shape)
rows, cols = df.shape
print(rows, cols)

데이터 크기: (200, 7)
200 7


In [48]:
# 모든 열(항목) 이름 출력
print("항목:", df.columns)
print("항목:", df.columns.tolist()) 
# index를 0,1,2 이런걸 사용하는게 아니라 측정시간, 압축압력 등의 제목이 곧 인덱스로 사용가능




항목: Index(['측정시각', '압축압력', '배출압력', '저장압력', '오일온도', '모터전류', '가동상태'], dtype='object')
항목: ['측정시각', '압축압력', '배출압력', '저장압력', '오일온도', '모터전류', '가동상태']


In [49]:
print(df["오일온도"].values) # numpy 배열임

[51.3 56.8 55.7  nan 55.3 57.1 56.6 56.6 57.2 57.4 57.7 57.2 58.9 57.6
 59.6 55.4 56.  56.  53.6 50.1 53.3 51.2 52.  50.4 51.  51.  50.5 51.8
 53.7 54.6 57.9 55.3 56.8 57.1 57.6 56.7 57.5 57.8 58.5 58.1 56.9 58.6
 58.5 56.6 57.4 53.8 55.5 55.  53.2 54.3 66.3 57.6 66.6 58.1 66.9 58.1
 67.2 58.9 67.2 59.5 67.5 59.6 65.5 65.8 62.6 71.8 61.2 71.2 60.6 70.6
 60.5 70.4 60.5 70.8 60.2 71.7 60.  71.4 59.1 67.6 57.4 65.1 69.6 67.9
 61.5 63.1 71.6 69.  70.6 62.2 68.1 69.8 73.2 61.3 73.  66.2 59.5 74.6
 67.  53.5 71.  60.6 70.6 72.  72.3 61.5 64.7 63.  63.7 75.  61.2 73.4
 63.9 70.8 67.3 63.1 66.5 60.2 64.7 69.2 71.8 67.5 68.3 72.6 62.9 64.
 61.4 58.8 67.2 61.1 66.8 57.3 61.8 66.7 67.2 61.1 64.1 60.9 66.2 65.
 67.7 61.3 72.8 67.6 64.5 72.7 70.7 71.8 71.6 61.  60.2 68.2 63.2 71.6
 59.7 66.3 58.8 73.1 61.7 64.8 61.6 66.1 75.  65.  73.6 68.5 69.7 68.1
 60.4 69.1 62.9 73.7 62.6 63.1 68.1 64.8 59.4 57.  63.3 65.9 64.1 60.3
 64.  65.2 70.5 58.7 58.8 71.5 70.2 64.3 69.1 73.4 62.7 60.6 67.5 60.7
 61.9 73

In [50]:
# "가동상태" 열의 고유값 개수와 고유갑별 총 갯수 출력

state = df["가동상태"].values

name, count = np.unique(state, return_counts=True)
print(name)
print(count)

['가동' '정지']
[ 96 104]


In [51]:
ele_motor = df["모터전류"].values

print(f'평균:{ele_motor.mean()}, 중앙값:{np.median(ele_motor)}, 분산:{ele_motor.var()}, 표준편차:{ele_motor.std()}')

평균:2.06085, 중앙값:0.04, 분산:4.8005107774999995, 표준편차:2.191006795402515


In [52]:
oil_temp=df['오일온도']
print(np.isnan(oil_temp))
# 이거는 배열의 값이 nan인지 확인하여 동일한 길이로 True, False의 배열로 변환

#True의 갯수를 알고싶다면 sum사용
# ex) np.isnan[ele_motor].sum(

#결측값 인덱스
print(np.where(np.isnan(oil_temp)))

0      False
1      False
2      False
3       True
4      False
       ...  
195    False
196    False
197    False
198    False
199    False
Name: 오일온도, Length: 200, dtype: bool
(array([3]),)


In [53]:
# head 사용해보기 -> 가장 위에서 5개행 반환
print(df.head())

                  측정시각  압축압력  배출압력  저장압력  오일온도  모터전류 가동상태
0  2020-02-27 06:38:47  9.30 -0.02  9.30  51.3  6.04   가동
1  2020-02-27 07:28:21  8.55 -0.02  8.55  56.8  0.04   정지
2  2020-02-27 08:17:54  8.67 -0.02  8.67  55.7  0.03   정지
3  2020-02-27 09:07:27  9.76 -0.02  9.76   NaN  3.81   가동
4  2020-02-27 09:57:01  8.49 -0.02  8.49  55.3  0.04   정지


In [54]:
#tail 사용해보기 -> 가장 아래에서 5개 행 반환

print(df.tail())

                    측정시각  압축압력  배출압력  저장압력  오일온도  모터전류 가동상태
195  2020-03-06 15:03:00  8.72 -0.02  8.72  60.7  5.81   가동
196  2020-03-06 15:52:33  8.85 -0.02  8.85  61.9  0.04   정지
197  2020-03-06 16:42:06  9.74 -0.02  9.74  73.0  3.77   가동
198  2020-03-06 17:31:39  9.89 -0.02  9.89  72.5  3.82   가동
199  2020-03-06 18:21:13  9.87 -0.02  9.87  71.7  3.75   가동


In [55]:
print(df.head(2)) 
#괄호안에 보고싶은 줄의 수를 넣으면 거기까지 출력해줌
# idx번호가 아니라 그냥 원하는 행의 갯수를 넣어야함
# tail도 마찬가지임

                  측정시각  압축압력  배출압력  저장압력  오일온도  모터전류 가동상태
0  2020-02-27 06:38:47  9.30 -0.02  9.30  51.3  6.04   가동
1  2020-02-27 07:28:21  8.55 -0.02  8.55  56.8  0.04   정지


In [56]:
# 실습1. 설비 센서 파일 불러와 확인하기
import pandas as pd
df = pd.read_csv("data/12_metro_compressor.csv")
print(df.shape)
print(df.head(15))

(200, 7)
                   측정시각  압축압력  배출압력  저장압력  오일온도  모터전류 가동상태
0   2020-02-27 06:38:47  9.30 -0.02  9.30  51.3  6.04   가동
1   2020-02-27 07:28:21  8.55 -0.02  8.55  56.8  0.04   정지
2   2020-02-27 08:17:54  8.67 -0.02  8.67  55.7  0.03   정지
3   2020-02-27 09:07:27  9.76 -0.02  9.76   NaN  3.81   가동
4   2020-02-27 09:57:01  8.49 -0.02  8.49  55.3  0.04   정지
5   2020-02-27 10:46:34  8.93 -0.02  8.93  57.1  0.04   정지
6   2020-02-27 11:36:07  9.96 -0.02  9.96  56.6  3.75   가동
7   2020-02-27 12:25:41  8.39 -0.02  8.40  56.6  0.04   정지
8   2020-02-27 13:15:15  8.47 -0.02  8.47  57.2  0.03   정지
9   2020-02-27 14:04:48  9.71 -0.02  9.71  57.4  6.07   가동
10  2020-02-27 14:54:22  8.64 -0.01  8.65  57.7  0.03   정지
11  2020-02-27 15:43:55  9.58 -0.02  9.58  57.2  3.73   가동
12  2020-02-27 16:33:29  8.57 -0.02  8.57  58.9  0.04   정지
13  2020-02-27 17:23:02  8.25 -0.02  8.25  57.6  5.86   가동
14  2020-02-27 18:12:37  9.32 -0.02  9.32  59.6  3.75   가동


In [57]:
import pandas as pd
df = pd.read_csv("data/12_metro_compressor_semicolon.csv", sep=";", usecols=['측정시각', '오일온도', '모터전류'])

print(df.shape)

df2 = pd.read_csv("data/12_metro_compressor_semicolon.csv", sep=";")
H = df2.head(20)

print(H.shape)

# 번호로 열을 고르면 데이터의 열 순서가 바뀌었을 때
# 원하지 않는 다른 열을 선택할 수 있어서 잘못되는 상황이 올 수 있다

(200, 3)
(20, 7)


In [58]:
df = pd.read_csv("data/12_metro_compressor_semicolon.csv", sep=";", usecols=['측정시각', '오일온도', '모터전류'], encoding='utf-8')
print(df.shape)

print(df.head(3))

(200, 3)
                  측정시각  오일온도  모터전류
0  2020-02-27 06:38:47  51.3  6.04
1  2020-02-27 07:28:21  56.8  0.04
2  2020-02-27 08:17:54  55.7  0.03


In [59]:

excel = pd.read_excel("data/12_metro_compressor.xlsx", sheet_name="12_metro_compressor")


In [60]:
output = df.to_csv("data/12_new.csv", index=False, encoding='utf-8-sig')
# 12_new.csv라는 이름으로 새로운 csv 파일 만들기

In [61]:
os.remove("data/12_new.csv")
# csv 파일 삭제하기

In [62]:
dfi = pd.read_csv("data/09_ict_inspection.csv")
print(dfi.info())

# 전체 17행, 부품명, 측정값, 기준값, 상한치, 하한치는 15행 -> 결측 10건


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   검사ID    17 non-null     int64  
 1   부품명     15 non-null     object 
 2   측정값     15 non-null     float64
 3   기준값     15 non-null     float64
 4   상한치     15 non-null     float64
 5   하한치     15 non-null     float64
 6   검사결과    17 non-null     object 
dtypes: float64(4), int64(1), object(2)
memory usage: 1.1+ KB
None


In [63]:
print(dfi.describe())

              검사ID          측정값          기준값          상한치          하한치
count    17.000000    15.000000    15.000000    15.000000    15.000000
mean   1961.352941  1897.682667  3852.333333  2618.000000 -4250.000000
std     739.232029  1674.064887  2243.970386   637.620577  1035.098339
min      -2.000000     0.000000    50.000000  2310.000000 -6250.000000
25%    2199.000000     0.000000  2425.000000  2310.000000 -3750.000000
50%    2212.000000  2712.470000  5000.000000  2310.000000 -3750.000000
75%    2225.000000  3069.680000  5000.000000  2310.000000 -3750.000000
max    2277.000000  4366.230000  7500.000000  3850.000000 -3750.000000


In [64]:
print(df)

                    측정시각  오일온도  모터전류
0    2020-02-27 06:38:47  51.3  6.04
1    2020-02-27 07:28:21  56.8  0.04
2    2020-02-27 08:17:54  55.7  0.03
3    2020-02-27 09:07:27   NaN  3.81
4    2020-02-27 09:57:01  55.3  0.04
..                   ...   ...   ...
195  2020-03-06 15:03:00  60.7  5.81
196  2020-03-06 15:52:33  61.9  0.04
197  2020-03-06 16:42:06  73.0  3.77
198  2020-03-06 17:31:39  72.5  3.82
199  2020-03-06 18:21:13  71.7  3.75

[200 rows x 3 columns]


In [65]:
df = pd.read_csv("data/12_metro_compressor_semicolon.csv", sep=";", encoding='utf-8')
print(df.head)

<bound method NDFrame.head of                     측정시각  압축압력  배출압력  저장압력  오일온도  모터전류 가동상태
0    2020-02-27 06:38:47  9.30 -0.02  9.30  51.3  6.04   가동
1    2020-02-27 07:28:21  8.55 -0.02  8.55  56.8  0.04   정지
2    2020-02-27 08:17:54  8.67 -0.02  8.67  55.7  0.03   정지
3    2020-02-27 09:07:27  9.76 -0.02  9.76   NaN  3.81   가동
4    2020-02-27 09:57:01  8.49 -0.02  8.49  55.3  0.04   정지
..                   ...   ...   ...   ...   ...   ...  ...
195  2020-03-06 15:03:00  8.72 -0.02  8.72  60.7  5.81   가동
196  2020-03-06 15:52:33  8.85 -0.02  8.85  61.9  0.04   정지
197  2020-03-06 16:42:06  9.74 -0.02  9.74  73.0  3.77   가동
198  2020-03-06 17:31:39  9.89 -0.02  9.89  72.5  3.82   가동
199  2020-03-06 18:21:13  9.87 -0.02  9.87  71.7  3.75   가동

[200 rows x 7 columns]>


In [66]:
# Pandas — 숫자 열 전부를 여덟 개 통계로 한 번에
print(df.describe())
# 더 파고들 때는 열 하나를 배열로 꺼내면 앞 단원 도구가 그대로
state = df['가동상태'].values
cur = df['모터전류'].values 

# 같은 인덱스의 다른 열을 가져옴
print(round(float(np.mean(cur[state == '가동'])), 2))   # 4.25

             압축압력        배출압력        저장압력        오일온도        모터전류
count  200.000000  200.000000  200.000000  199.000000  200.000000
mean     9.172200   -0.016950    9.171400   63.181910    2.060850
std      0.583699    0.047173    0.582497    6.249822    2.196505
min      8.130000   -0.030000    8.130000   50.100000    0.030000
25%      8.700000   -0.020000    8.697500   58.100000    0.040000
50%      9.175000   -0.020000    9.175000   62.900000    0.040000
75%      9.665000   -0.020000    9.655000   68.100000    3.812500
max     10.220000    0.600000   10.220000   75.000000    6.190000
4.25


In [67]:
# 가동상태일때의 모든 저장압력값 평균 구하기
pres_s = df['저장압력'].values
print(round(float(np.mean(pres_s[state == '가동'])), 2))


9.61


In [68]:
state = df['가동상태'].values
cur = df['모터전류'].values 

print(round(df.describe(),2))
#             압축압력   배출압력   저장압력  오일온도  모터전류
#   mean        9.17     -0.02      9.17   63.18     2.06
#   median      9.18      -0.02     9.18   62.90     0.04

state = df['가동상태'].values
cur = df['모터전류'].values 
cur_on = cur[state == '가동']
cur_off = cur[state == '정지']

print("가동 시 모터전류 평균:",round(float(np.mean(cur[state == '가동'])), 2))
print("정지 시 모터전류 평균:",round(float(np.mean(cur[state == '정지'])), 2))


         압축압력    배출압력    저장압력    오일온도    모터전류
count  200.00  200.00  200.00  199.00  200.00
mean     9.17   -0.02    9.17   63.18    2.06
std      0.58    0.05    0.58    6.25    2.20
min      8.13   -0.03    8.13   50.10    0.03
25%      8.70   -0.02    8.70   58.10    0.04
50%      9.18   -0.02    9.18   62.90    0.04
75%      9.66   -0.02    9.66   68.10    3.81
max     10.22    0.60   10.22   75.00    6.19
가동 시 모터전류 평균: 4.25
정지 시 모터전류 평균: 0.04


In [69]:
df= pd.read_csv("data/12_metro_compressor_semicolon.csv", sep=";", encoding='utf-8')
df2 = pd.read_csv("data/12_metro_digital.csv", encoding='utf-8')

print(df.shape, "Vs", df2.shape)
print(df.info())
print(df2.info())


(200, 7) Vs (120, 4)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   측정시각    200 non-null    object 
 1   압축압력    200 non-null    float64
 2   배출압력    200 non-null    float64
 3   저장압력    200 non-null    float64
 4   오일온도    199 non-null    float64
 5   모터전류    200 non-null    float64
 6   가동상태    200 non-null    object 
dtypes: float64(5), object(2)
memory usage: 11.1+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   측정시각    120 non-null    object
 1   압축기     120 non-null    int64 
 2   타워      120 non-null    int64 
 3   저압스위치   120 non-null    int64 
dtypes: int64(3), object(1)
memory usage: 3.9+ KB
None


In [70]:
df = pd.read_csv("data/13_diecasting_small.csv")

print(type(df))
print(type(df['형체력']))
print(df['형체력'].head(3))

print(type(df[['형체력', '실린더압력']]))
print(df[['형체력', '실린더압력']].shape)

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>
0    258.0
1    257.0
2    253.0
Name: 형체력, dtype: float64
<class 'pandas.core.frame.DataFrame'>
(30, 2)


In [71]:
# ===============================
# loc
# 라벨로 값을 불러오는 도구를 의미한다
# 끝라벨 포함
print(df.loc[0]) # 현재 data set에서 0번째 행에 대한 값들을 출력
# print(df.loc['품질등급'])


# iloc
# 위치로 값을 불러오는 도구를 의미한다
# 끝 라벨 포함 X
# integer의 약자인 i가 붙어서 인자로 무조건 정수만 작성 가능
print(df.iloc)

샷               1
설비ID     DIE-B-02
실린더압력       214.0
주조압력       1037.0
사이클타임        20.7
비스킷두께        10.0
형체력         258.0
품질등급           양품
Name: 0, dtype: object


In [72]:
sorted_df = df.sort_values('형체력', ascending=False) #내림차순 정렬

print('형체력 기준 내림차순 정렬 결과 위치 0~4까지 출력')
print(sorted_df.index[:4])

형체력 기준 내림차순 정렬 결과 위치 0~4까지 출력
Index([22, 17, 27, 12], dtype='int64')


In [73]:
df = pd.read_csv('data/13_diecasting_small.csv')
print(df.loc[0, '샷'])       
print(df.iloc[0]['샷'])      
sorted_df = df.sort_values('형체력', ascending=False)
print(sorted_df.loc[0, '샷'])
print(sorted_df.iloc[0]['샷'])
print(sorted_df.index[:3].tolist())

1
1
1
23
[22, 17, 27]


In [74]:
df = pd.read_csv('data/13_diecasting_small.csv')
print(list(df.columns))
t = df.loc[0:4, ['실린더압력','형체력']]
print(t.shape)

y=df.iloc[0:5, [2,6]]
print(y.shape)

print(t.equals(y))

['샷', '설비ID', '실린더압력', '주조압력', '사이클타임', '비스킷두께', '형체력', '품질등급']
(5, 2)
(5, 2)
True


In [75]:
df = pd.read_csv('data/13_diecasting_shot.csv')
print(df.shape)
print(list(df.columns))

forward10 = df.loc[:9, ['설비ID', '비스킷두께', '품질등급']]
print(forward10)

last5 = df.iloc[-5:]
print(last5)

(200, 8)
['샷', '설비ID', '실린더압력', '주조압력', '사이클타임', '비스킷두께', '형체력', '품질등급']
       설비ID  비스킷두께 품질등급
0  DIE-A-01   10.0   양품
1  DIE-B-01   11.0   양품
2  DIE-B-01   11.0   양품
3  DIE-B-02   11.0   양품
4  DIE-A-01   11.0   양품
5  DIE-A-01   11.0   양품
6  DIE-A-01   11.0   양품
7  DIE-A-01   11.0   양품
8  DIE-B-02   11.0   양품
9  DIE-A-01   12.0   양품
       샷      설비ID  실린더압력   주조압력   사이클타임  비스킷두께    형체력 품질등급
195  196  DIE-A-01  264.0  594.0    76.3   19.0  381.0   불량
196  197  DIE-A-01  265.0  595.0    36.2   20.0  355.0   불량
197  198  DIE-A-01  113.0  255.0    36.6   27.0  354.0   불량
198  199  DIE-B-02  264.0  595.0    36.1   19.0  372.0   불량
199  200  DIE-A-01  108.0  525.0  6170.0   15.0  237.0   불량


In [77]:
# 1. 품질등급이 양품인 것들을 뽑아서
# 실린더압력, 주조압력, 사이클타임, 비스킷두께, 형체력의 정보 도출
# 품질등급이 불량니 것들을 뽑아서 실린더 압력, 주조압력, 사이클타임, 비스킷 두께, 형체력의 정보 도출
# 본인이 생각하는 중요한 항목과 정상범위를 선정해서
# 해당 항목의 정상범위 품질 등급별 갯수 출력

df = pd.read_csv('data/13_diecasting_shot.csv')
pressure_cyl = df['실린더압력']
pressure_ju = df['주조압력']
ct = df['사이클타임']
bis = df['비스킷두께']
force=df['형체력']
state = df['품질등급']
df_ok = df[state == '양품']
df_notok = df[state == '불량']

print(df_ok.info())
print(df_notok.info())

# 내가 생각하는 중요한 항목 = 실린더압력, 사이클타임
# 정상 범위: 실린더압력 = 210이상 270이하, 사이클타임 = 20이상 40이하

normal_range = df[
    (df["실린더압력"] >= 210) &
    (df["실린더압력"] <= 270) &
    (df["사이클타임"] >= 20) &
    (df["사이클타임"] <= 40)]

print(normal_range['품질등급'].value_counts())

<class 'pandas.core.frame.DataFrame'>
Index: 162 entries, 0 to 179
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   샷       162 non-null    int64  
 1   설비ID    162 non-null    object 
 2   실린더압력   151 non-null    float64
 3   주조압력    151 non-null    float64
 4   사이클타임   151 non-null    float64
 5   비스킷두께   151 non-null    float64
 6   형체력     151 non-null    float64
 7   품질등급    162 non-null    object 
dtypes: float64(5), int64(1), object(2)
memory usage: 11.4+ KB
None
<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, 180 to 199
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   샷       20 non-null     int64  
 1   설비ID    20 non-null     object 
 2   실린더압력   17 non-null     float64
 3   주조압력    17 non-null     float64
 4   사이클타임   17 non-null     float64
 5   비스킷두께   17 non-null     float64
 6   형체력     17 non-null     float64
 7   품질등급    20 non-null     o

In [ ]:
state = df['가동상태'].values
cur = df['모터전류'].values 
cur_on = cur[state == '가동']
cur_off = cur[state == '정지']
bis = 